"""Generate COVERAGE.md from the bundled active release (or a given release file).

The page is derived from the served data so that it cannot drift from it.
Regenerate it whenever a release is published.
"""

import argparse
from collections import defaultdict
from datetime import datetime, timedelta, timezone
import json
from pathlib import Path

from swisstip.mcp_server.bundled import bundled_releases, read_manifest, sha256
from swisstip.runtime.release import ReleaseBundle
from swisstip.runtime.service import coverage_summary

ROOT = Path(__file__).resolve().parents[2]

CANTON_NAMES = {
    "CH-AG": "Aargau", "CH-AI": "Appenzell Innerrhoden", "CH-AR": "Appenzell Ausserrhoden", "CH-BE": "Bern",
    "CH-BL": "Basel-Landschaft", "CH-BS": "Basel-Stadt", "CH-FR": "Fribourg", "CH-GE": "Geneva", "CH-GL": "Glarus",
    "CH-GR": "Graubunden", "CH-JU": "Jura", "CH-LU": "Lucerne", "CH-NE": "Neuchatel", "CH-NW": "Nidwalden",
    "CH-OW": "Obwalden", "CH-SG": "St Gallen", "CH-SH": "Schaffhausen", "CH-SO": "Solothurn", "CH-SZ": "Schwyz",
    "CH-TG": "Thurgau", "CH-TI": "Ticino", "CH-UR": "Uri", "CH-VD": "Vaud", "CH-VS": "Valais", "CH-ZG": "Zug", "CH-ZH": "Zurich",
}


LEVEL_RANK = {"Federal": 0, "Canton ": 1, "Municipality": 2, "Cantonal": 3}


def level_rank(name: str) -> tuple[int, str]:
    return next((rank for prefix, rank in LEVEL_RANK.items() if name.startswith(prefix)), 9), name


def plain(text: str) -> str:
    """Repository text uses ASCII hyphens; normalise dashes in quoted titles."""
    return text.replace("–", "-").replace("—", "-")


def describe(jurisdiction) -> str:
    if jurisdiction.canton_code is None:
        return "Federal (applies in every canton)"
    canton = CANTON_NAMES.get(jurisdiction.canton_code, jurisdiction.canton_code)
    if jurisdiction.municipality_id is None:
        return f"Canton {canton} ({jurisdiction.canton_code})"
    return f"Municipality {jurisdiction.municipality_id} in Canton {canton}"


def report(bundle: ReleaseBundle, release_sha: str, manifest_entry: dict | None, releases_dir: Path) -> str:
    catalog, release = bundle.catalog, bundle.release
    labels = {e.entry_id: e for e in catalog.entries}
    schemas = {s.identity: s for s in catalog.context_schemas}
    plans = {p.coverage_profile_id: p for p in bundle.graph.plans}
    rules = {r.identity: r for r in bundle.rules}
    facts = {f.fact_id: f for f in bundle.facts}
    evidence_by_id = {e.evidence_id: e for e in bundle.evidence}
    accessed = sorted(e.citation.accessed_at for e in bundle.evidence)
    oldest = datetime.fromisoformat(accessed[0].replace("Z", "+00:00"))
    freshness_days = sorted({p.freshness_policy.max_age_days for p in catalog.coverage_profiles})
    stale_from = (oldest + timedelta(days=min(freshness_days))).astimezone(timezone.utc)

    lines = []
    out = lines.append
    out("# Coverage")
    out("")
    out("Generated by `scripts/releases/coverage_report.py` from the bundled release; do not edit by hand.")
    out("")
    out("| Item | Value |")
    out("| --- | --- |")
    out(f"| Release ID | `{release.release_id}` |")
    out(f"| Release SHA-256 | `{release_sha}` |")
    out(f"| Built | {release.created_at} |")
    saved = accessed[0][:10] if accessed[0][:10] == accessed[-1][:10] else f"{accessed[0][:10]} to {accessed[-1][:10]}"
    out(f"| Source pages saved | {saved} |")
    out(f"| Documents / concepts / facts / evidence spans / rules / coverage profiles | {len(bundle.documents)} / "
        f"{sum(1 for e in catalog.entries if e.kind == 'concept')} / {len(bundle.facts)} / {len(bundle.evidence)} / "
        f"{len(bundle.rules)} / {len(catalog.coverage_profiles)} |")
    out(f"| Evidence languages | {', '.join(sorted({e.effective_source_language for e in bundle.evidence}))} |")
    out(f"| Fact statement language | {', '.join(sorted({f.language for f in bundle.facts}))} (paraphrases of the cited original spans) |")
    out(f"| Catalog label languages | {', '.join(sorted({lang for e in catalog.entries for lang in e.labels}))} |")
    out(f"| Retrieval-term languages | {', '.join(bundle.language_policy.term_languages) or 'none (retrieval terms are not supported by this release)'} |")
    out(f"| Intents | {', '.join(sorted({p.intent for p in catalog.coverage_profiles}))} |")
    out(f"| Freshness policy | {' or '.join(str(d) for d in freshness_days)} days from the saved copy; results report `STALE` from {stale_from.strftime('%Y-%m-%d %H:%M')} UTC |")
    if manifest_entry:
        out(f"| Published into `releases/` | {manifest_entry['published_at']} from `{manifest_entry['source']}` |")
    out("")
    out("## Sources")
    out("")
    out("| Authority | Language | Page |")
    out("| --- | --- | --- |")
    sources = sorted({(e.citation.authority, e.effective_source_language, e.citation.url, e.citation.title) for e in bundle.evidence})
    for authority, language, url, title in sources:
        out(f"| {plain(authority)} | {language} | [{plain(title)}]({url}) |")
    out("")
    out("## Jurisdictions")
    out("")
    out("A coverage profile serves every place inside its own jurisdiction: a federal profile answers for any canton or "
        "municipality, a cantonal profile for its municipalities, never upward or sideways. When a wider profile answers, "
        "`executed_scope` reports its level and a limitation says that the more specific place is not covered.")
    out("")
    levels = defaultdict(list)
    for profile in catalog.coverage_profiles:
        levels[describe(profile.jurisdiction) if profile.intent != "contacts" else "Cantonal migration-office contacts"].append(profile)
    out("| Level | Coverage profiles |")
    out("| --- | --- |")
    for level in sorted(levels, key=level_rank):
        out(f"| {level} | {len(levels[level])} |")
    out("")
    out("## Concepts")
    out("")
    out("Each row is one concept a caller can resolve. Required context fields must be supplied; `-` means none. "
        "Population and sponsor values route to pre-authored statements and do not decide eligibility.")
    out("")
    for level in sorted(levels, key=level_rank):
        profiles = [p for p in levels[level] if p.intent != "contacts"]
        if not profiles:
            continue
        out(f"### {level}")
        out("")
        out("| Concept | Label | Intent | Required context | Facts | Validity |")
        out("| --- | --- | --- | --- | --- | --- |")
        for profile in sorted(profiles, key=lambda p: p.concept_ids[0]):
            concept = profile.concept_ids[0]
            schema = schemas[profile.context_schema_ref]
            context = "; ".join(f"`{f.name}` in {', '.join(f.enum or [])}" for f in schema.fields if f.required) or "-"
            plan = plans[profile.coverage_profile_id]
            fact_ids = [f for portion in plan.portions for f in portion.fact_ids]
            fact_ids += [f for portion in plan.portions for ref in portion.rule_refs for f in rules[ref].fact_ids]
            window = profile.temporal_coverage
            validity = ("any date" if window.valid_from is None and window.valid_through is None
                        else " ".join(filter(None, [f"from {window.valid_from}" if window.valid_from else None,
                                                    f"through {window.valid_through}" if window.valid_through else None])))
            label = list(labels[concept].labels.values())[0].label
            out(f"| `{concept}` | {label} | {profile.intent} | {context} | {len(fact_ids)} | {validity} |")
        out("")
    contacts = sorted((p for p in catalog.coverage_profiles if p.intent == "contacts"), key=lambda p: p.jurisdiction.canton_code)
    if contacts:
        out("### Cantonal migration-office contacts")
        out("")
        out("One `contacts` profile per canton, from the SEM directory of cantonal authorities: "
            + ", ".join(f"{CANTON_NAMES.get(p.jurisdiction.canton_code, p.jurisdiction.canton_code)} ({p.jurisdiction.canton_code})" for p in contacts) + ".")
        out("")
    out("## Validity and freshness")
    out("")
    out("Validity is unbounded unless the cited source states a commencement or expiry date; `as_of` is the applicability "
        "date the caller asks about, normally today. Freshness measures the age of the saved copy of each page, not whether "
        "the page changed; a result older than the policy allows is reported `STALE` with its facts retained.")
    stated = [(p.concept_ids[0], p.temporal_coverage) for p in catalog.coverage_profiles
              if p.temporal_coverage.valid_from or p.temporal_coverage.valid_through]
    if stated:
        out("")
        out("Source-stated limits: " + "; ".join(
            f"`{concept}` " + " ".join(filter(None, [f"from {w.valid_from}" if w.valid_from else None,
                                                    f"through {w.valid_through}" if w.valid_through else None]))
            for concept, w in sorted(stated)) + ".")
    out("")
    out("## Scope")
    out("")
    summary = coverage_summary(bundle)
    if summary.scope:
        out("Declared in the release and served verbatim in `coverage_summary` of the root `get_coverage` result.")
        for language, text in summary.scope.items():
            out("")
            out(f"**In scope ({language}).** {text}")
            out("")
            out(f"**Out of scope ({language}).**")
            out("")
            for item in summary.out_of_scope.get(language, []):
                out(f"- {item}")
    else:
        out("This release publishes no scope statement; the root `get_coverage` result carries only derived limits.")
    out("")
    out("Derived limits, computed from the release at serving time:")
    out("")
    for item in summary.derived_limits:
        out(f"- {item}")
    out("")
    out("Served jurisdictions, grouped by level and intent:")
    out("")
    out("| Level | Intent | Concepts each | Places |")
    out("| --- | --- | --- | --- |")
    for row in summary.jurisdictions:
        first = row.jurisdictions[0]
        level = ("Federal" if first.specificity == 0 else "Canton" if first.specificity == 1 else "Municipality")
        names = ", ".join(f"{j.canton_code}/{j.municipality_id}" if j.municipality_id else j.canton_code or j.country_code
                          for j in row.jurisdictions)
        out(f"| {level} | {row.intent} | {row.concept_count} | {names} |")
    out("")
    out("## Example request")
    out("")
    requests_path = releases_dir / release.release_id / "mcp-requests.json"
    sample = None
    if requests_path.is_file():
        prepared = json.loads(requests_path.read_text(encoding="utf-8"))["resolve"]
        sample = next((r for r in prepared if r["name"] == "eu-employment-registration-deadline"), None)
    if sample:
        out("`resolve` arguments for the EU/EFTA registration deadline (add the user's canton or municipality to `jurisdiction` when known):")
        out("")
        out("```json")
        out(json.dumps(sample["arguments"], indent=2))
        out("```")
        out("")
    out(f"Evidence objects: {len(evidence_by_id)}; every fact cites at least one exact span of a saved official page with URL, authority and access time.")
    out("")
    return "\n".join(lines)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--release", type=Path, help="Release file; default: the bundled active release")
    parser.add_argument("--output", type=Path, default=ROOT / "COVERAGE.md")
    args = parser.parse_args(argv)
    manifest_entry = None
    releases_dir = ROOT / "releases"
    if args.release:
        path = args.release.resolve()
    else:
        paths, active = bundled_releases()
        releases_dir, manifest = read_manifest()
        path = next(p for p in paths if p.parent.name == active)
        manifest_entry = next(e for e in manifest["releases"] if e["release_id"] == active)
    bundle = ReleaseBundle.model_validate_json(path.read_bytes())
    text = report(bundle, sha256(path), manifest_entry, releases_dir)
    args.output.write_text(text, encoding="utf-8", newline="\n")
    print(f"Wrote {args.output} for {bundle.release.release_id}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
