// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AddReviewData, AddReviewErrors, AddReviewResponses, CancelJobData, CancelJobErrors, CancelJobResponses, CreateJobData, CreateJobErrors, CreateJobResponses, GetAssetsData, GetAssetsResponses, GetCatalogData, GetCatalogResponses, GetJobData, GetJobErrors, GetJobResponses, GetJobsData, GetJobsResponses, GetReleaseEvidenceData, GetReleaseEvidenceErrors, GetReleaseEvidenceResponses, GetReleasesData, GetReleasesResponses, GetReviewsData, GetReviewsErrors, GetReviewsResponses, LoadPilotAssetsData, LoadPilotAssetsErrors, LoadPilotAssetsResponses, PreviewAssetData, PreviewAssetErrors, PreviewAssetResponses, UploadAssetData, UploadAssetErrors, UploadAssetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Catalog
 */
export const getCatalog = <ThrowOnError extends boolean = false>(options?: Options<GetCatalogData, ThrowOnError>): RequestResult<GetCatalogResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetCatalogResponses, unknown, ThrowOnError>({ url: '/api/catalog', ...options });

/**
 * Assets
 */
export const getAssets = <ThrowOnError extends boolean = false>(options?: Options<GetAssetsData, ThrowOnError>): RequestResult<GetAssetsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetAssetsResponses, unknown, ThrowOnError>({ url: '/api/assets', ...options });

/**
 * Upload Asset
 */
export const uploadAsset = <ThrowOnError extends boolean = false>(options: Options<UploadAssetData, ThrowOnError>): RequestResult<UploadAssetResponses, UploadAssetErrors, ThrowOnError> => (options.client ?? client).post<UploadAssetResponses, UploadAssetErrors, ThrowOnError>({
    url: '/api/assets',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Load Pilot
 */
export const loadPilotAssets = <ThrowOnError extends boolean = false>(options: Options<LoadPilotAssetsData, ThrowOnError>): RequestResult<LoadPilotAssetsResponses, LoadPilotAssetsErrors, ThrowOnError> => (options.client ?? client).post<LoadPilotAssetsResponses, LoadPilotAssetsErrors, ThrowOnError>({
    url: '/api/assets/pilot',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Preview
 */
export const previewAsset = <ThrowOnError extends boolean = false>(options: Options<PreviewAssetData, ThrowOnError>): RequestResult<PreviewAssetResponses, PreviewAssetErrors, ThrowOnError> => (options.client ?? client).get<PreviewAssetResponses, PreviewAssetErrors, ThrowOnError>({ url: '/api/assets/{identifier}/preview', ...options });

/**
 * List Jobs
 */
export const getJobs = <ThrowOnError extends boolean = false>(options?: Options<GetJobsData, ThrowOnError>): RequestResult<GetJobsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetJobsResponses, unknown, ThrowOnError>({ url: '/api/jobs', ...options });

/**
 * Create Job
 */
export const createJob = <ThrowOnError extends boolean = false>(options: Options<CreateJobData, ThrowOnError>): RequestResult<CreateJobResponses, CreateJobErrors, ThrowOnError> => (options.client ?? client).post<CreateJobResponses, CreateJobErrors, ThrowOnError>({
    url: '/api/jobs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Job
 */
export const getJob = <ThrowOnError extends boolean = false>(options: Options<GetJobData, ThrowOnError>): RequestResult<GetJobResponses, GetJobErrors, ThrowOnError> => (options.client ?? client).get<GetJobResponses, GetJobErrors, ThrowOnError>({ url: '/api/jobs/{identifier}', ...options });

/**
 * Cancel Job
 */
export const cancelJob = <ThrowOnError extends boolean = false>(options: Options<CancelJobData, ThrowOnError>): RequestResult<CancelJobResponses, CancelJobErrors, ThrowOnError> => (options.client ?? client).post<CancelJobResponses, CancelJobErrors, ThrowOnError>({
    url: '/api/jobs/{identifier}/cancel',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reviews
 */
export const getReviews = <ThrowOnError extends boolean = false>(options: Options<GetReviewsData, ThrowOnError>): RequestResult<GetReviewsResponses, GetReviewsErrors, ThrowOnError> => (options.client ?? client).get<GetReviewsResponses, GetReviewsErrors, ThrowOnError>({ url: '/api/jobs/{identifier}/reviews', ...options });

/**
 * Review
 */
export const addReview = <ThrowOnError extends boolean = false>(options: Options<AddReviewData, ThrowOnError>): RequestResult<AddReviewResponses, AddReviewErrors, ThrowOnError> => (options.client ?? client).post<AddReviewResponses, AddReviewErrors, ThrowOnError>({
    url: '/api/jobs/{identifier}/reviews',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Releases
 */
export const getReleases = <ThrowOnError extends boolean = false>(options?: Options<GetReleasesData, ThrowOnError>): RequestResult<GetReleasesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetReleasesResponses, unknown, ThrowOnError>({ url: '/api/releases', ...options });

/**
 * Evidence
 */
export const getReleaseEvidence = <ThrowOnError extends boolean = false>(options: Options<GetReleaseEvidenceData, ThrowOnError>): RequestResult<GetReleaseEvidenceResponses, GetReleaseEvidenceErrors, ThrowOnError> => (options.client ?? client).get<GetReleaseEvidenceResponses, GetReleaseEvidenceErrors, ThrowOnError>({ url: '/api/releases/{identifier}/evidence', ...options });
