// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

/**
 * ActionRequest
 */
export type ActionRequest = {
    [key: string]: never;
};

/**
 * Asset
 */
export type Asset = {
    /**
     * Asset Id
     */
    asset_id: string;
    /**
     * Source Id
     */
    source_id: string;
    /**
     * Filename
     */
    filename: string;
    /**
     * Sha256
     */
    sha256: string;
    /**
     * Origin
     */
    origin: string;
    /**
     * Size
     */
    size: number;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * Catalog
 */
export type Catalog = {
    /**
     * Sources
     */
    sources: Array<Source>;
    /**
     * Profiles
     */
    profiles: Array<Profile>;
    /**
     * Crawl Profiles
     */
    crawl_profiles: Array<string>;
    /**
     * Max Pages
     */
    max_pages: number;
    /**
     * Max Requests
     */
    max_requests: number;
};

/**
 * Evidence
 */
export type Evidence = {
    /**
     * Evidence Id
     */
    evidence_id: string;
    /**
     * Source Id
     */
    source_id: string;
    /**
     * Language
     */
    language: string;
    /**
     * Original Excerpt
     */
    original_excerpt: string;
    /**
     * Citation Url
     */
    citation_url: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Job
 */
export type Job = {
    /**
     * Job Id
     */
    job_id: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * Status
     */
    status: string;
    /**
     * Request
     */
    request: {
        [key: string]: unknown;
    };
    /**
     * Log
     */
    log: string;
    /**
     * Result
     */
    result: {
        [key: string]: unknown;
    } | null;
    /**
     * Result Sha256
     */
    result_sha256?: string | null;
    /**
     * Error
     */
    error: string | null;
    /**
     * Cancel Requested
     */
    cancel_requested: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Started At
     */
    started_at: string | null;
    /**
     * Finished At
     */
    finished_at: string | null;
};

/**
 * JobRequest
 */
export type JobRequest = {
    /**
     * Kind
     */
    kind: 'crawl' | 'plan' | 'extract';
    /**
     * Source Ids
     */
    source_ids?: Array<string>;
    /**
     * Asset Ids
     */
    asset_ids?: Array<string>;
    /**
     * Profile
     */
    profile?: string;
    /**
     * Crawl Profile
     */
    crawl_profile?: 'smoke';
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * Preview
 */
export type Preview = {
    /**
     * Title
     */
    title: string;
    /**
     * Language
     */
    language: string | null;
    /**
     * Sections
     */
    sections: Array<Section>;
    /**
     * Characters
     */
    characters: number;
    /**
     * Excluded Sections
     */
    excluded_sections: number;
};

/**
 * Profile
 */
export type Profile = {
    /**
     * Name
     */
    name: string;
    /**
     * Adapter
     */
    adapter: string;
    /**
     * Model
     */
    model: string;
    /**
     * Credential Ready
     */
    credential_ready: boolean;
    /**
     * Selected
     */
    selected: boolean;
};

/**
 * Release
 */
export type Release = {
    /**
     * Release Id
     */
    release_id: string;
    /**
     * Classification
     */
    classification: string;
    /**
     * Evidence Count
     */
    evidence_count: number;
    /**
     * Imported At
     */
    imported_at: string;
};

/**
 * ReviewRequest
 */
export type ReviewRequest = {
    /**
     * Result Sha256
     */
    result_sha256: string;
    /**
     * Candidate Id
     */
    candidate_id: string;
    /**
     * Reviewer
     */
    reviewer: string;
    /**
     * Decision
     */
    decision: 'accept_draft' | 'reject' | 'needs_changes';
    /**
     * Notes
     */
    notes?: string;
};

/**
 * Section
 */
export type Section = {
    /**
     * Section Id
     */
    section_id: string;
    /**
     * Text
     */
    text: string;
};

/**
 * Source
 */
export type Source = {
    /**
     * Source Id
     */
    source_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Language
     */
    language: string;
    /**
     * Url
     */
    url: string;
    /**
     * Scan Status
     */
    scan_status: string;
    /**
     * Selected
     */
    selected: boolean;
};

/**
 * UploadRequest
 */
export type UploadRequest = {
    /**
     * Source Id
     */
    source_id: string;
    /**
     * Filename
     */
    filename: string;
    /**
     * Text
     */
    text: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type GetCatalogData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/catalog';
};

export type GetCatalogResponses = {
    /**
     * Successful Response
     */
    200: Catalog;
};

export type GetCatalogResponse = GetCatalogResponses[keyof GetCatalogResponses];

export type GetAssetsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/assets';
};

export type GetAssetsResponses = {
    /**
     * Response Getassets
     *
     * Successful Response
     */
    200: Array<Asset>;
};

export type GetAssetsResponse = GetAssetsResponses[keyof GetAssetsResponses];

export type UploadAssetData = {
    body: UploadRequest;
    path?: never;
    query?: never;
    url: '/api/assets';
};

export type UploadAssetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadAssetError = UploadAssetErrors[keyof UploadAssetErrors];

export type UploadAssetResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UploadAssetResponse = UploadAssetResponses[keyof UploadAssetResponses];

export type LoadPilotAssetsData = {
    body: ActionRequest;
    path?: never;
    query?: never;
    url: '/api/assets/pilot';
};

export type LoadPilotAssetsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoadPilotAssetsError = LoadPilotAssetsErrors[keyof LoadPilotAssetsErrors];

export type LoadPilotAssetsResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoadPilotAssetsResponse = LoadPilotAssetsResponses[keyof LoadPilotAssetsResponses];

export type PreviewAssetData = {
    body?: never;
    path: {
        /**
         * Identifier
         */
        identifier: string;
    };
    query?: never;
    url: '/api/assets/{identifier}/preview';
};

export type PreviewAssetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PreviewAssetError = PreviewAssetErrors[keyof PreviewAssetErrors];

export type PreviewAssetResponses = {
    /**
     * Successful Response
     */
    200: Preview;
};

export type PreviewAssetResponse = PreviewAssetResponses[keyof PreviewAssetResponses];

export type GetJobsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/jobs';
};

export type GetJobsResponses = {
    /**
     * Response Getjobs
     *
     * Successful Response
     */
    200: Array<Job>;
};

export type GetJobsResponse = GetJobsResponses[keyof GetJobsResponses];

export type CreateJobData = {
    body: JobRequest;
    path?: never;
    query?: never;
    url: '/api/jobs';
};

export type CreateJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateJobError = CreateJobErrors[keyof CreateJobErrors];

export type CreateJobResponses = {
    /**
     * Successful Response
     */
    202: Job;
};

export type CreateJobResponse = CreateJobResponses[keyof CreateJobResponses];

export type GetJobData = {
    body?: never;
    path: {
        /**
         * Identifier
         */
        identifier: string;
    };
    query?: never;
    url: '/api/jobs/{identifier}';
};

export type GetJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetJobError = GetJobErrors[keyof GetJobErrors];

export type GetJobResponses = {
    /**
     * Successful Response
     */
    200: Job;
};

export type GetJobResponse = GetJobResponses[keyof GetJobResponses];

export type CancelJobData = {
    body: ActionRequest;
    path: {
        /**
         * Identifier
         */
        identifier: string;
    };
    query?: never;
    url: '/api/jobs/{identifier}/cancel';
};

export type CancelJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelJobError = CancelJobErrors[keyof CancelJobErrors];

export type CancelJobResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type CancelJobResponse = CancelJobResponses[keyof CancelJobResponses];

export type GetReviewsData = {
    body?: never;
    path: {
        /**
         * Identifier
         */
        identifier: string;
    };
    query?: never;
    url: '/api/jobs/{identifier}/reviews';
};

export type GetReviewsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetReviewsError = GetReviewsErrors[keyof GetReviewsErrors];

export type GetReviewsResponses = {
    /**
     * Response Getreviews
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type GetReviewsResponse = GetReviewsResponses[keyof GetReviewsResponses];

export type AddReviewData = {
    body: ReviewRequest;
    path: {
        /**
         * Identifier
         */
        identifier: string;
    };
    query?: never;
    url: '/api/jobs/{identifier}/reviews';
};

export type AddReviewErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddReviewError = AddReviewErrors[keyof AddReviewErrors];

export type AddReviewResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type AddReviewResponse = AddReviewResponses[keyof AddReviewResponses];

export type GetReleasesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/releases';
};

export type GetReleasesResponses = {
    /**
     * Response Getreleases
     *
     * Successful Response
     */
    200: Array<Release>;
};

export type GetReleasesResponse = GetReleasesResponses[keyof GetReleasesResponses];

export type GetReleaseEvidenceData = {
    body?: never;
    path: {
        /**
         * Identifier
         */
        identifier: string;
    };
    query?: never;
    url: '/api/releases/{identifier}/evidence';
};

export type GetReleaseEvidenceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetReleaseEvidenceError = GetReleaseEvidenceErrors[keyof GetReleaseEvidenceErrors];

export type GetReleaseEvidenceResponses = {
    /**
     * Response Getreleaseevidence
     *
     * Successful Response
     */
    200: Array<Evidence>;
};

export type GetReleaseEvidenceResponse = GetReleaseEvidenceResponses[keyof GetReleaseEvidenceResponses];
